openapi: "3.0.0"
info:
  version: "0.1"
  title: "Homekids"
servers:
  - url: "http://localhost/api/client/v1"
    description: "local"
paths:
  /users/login:
    post:
      tags:
      - User
      summary: "Login into account"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                login: 
                  type: string
                password:
                  type: string
              required:
              - login
              - password
      responses:
        200: 
          description: "OK"

  /users/check:
    post:
      tags:
      - User
      summary: "Check if token is valid"
      security:
      - bearerAuth: []
      responses:
        200: 
          description: "OK"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  responses:
    UnauthorizedError:
      description: "Access token is missing or invalid"