openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost:8081'
paths:
  '/api/client/v1/dictionary-categories/{category}/dictionaries':
    get:
      summary: 'Получить словарь по категории'
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  error: null
                  data:
                    -
                      id: 6
                      label: 'Район №1'
                    -
                      id: 7
                      label: 'Район №2'
                    -
                      id: 8
                      label: 'Район №3'
                    -
                      id: 9
                      label: 'Район №4'
                    -
                      id: 10
                      label: 'Район №5'
                properties:
                  error:
                    type: string
                    example: null
                  data:
                    type: array
                    example:
                      -
                        id: 6
                        label: 'Район №1'
                      -
                        id: 7
                        label: 'Район №2'
                      -
                        id: 8
                        label: 'Район №3'
                      -
                        id: 9
                        label: 'Район №4'
                      -
                        id: 10
                        label: 'Район №5'
                    items:
                      type: object
      tags:
        - 'Категории словарей'
    parameters:
      -
        in: path
        name: category
        description: 'Категория (district | organization-type)'
        example: district
        required: true
        schema:
          type: string
  /api/client/v1/company:
    get:
      summary: 'Получить компанию авторизованного юзера'
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  error: null
                  data:
                    id: 1
                    name: 'Компания 1'
                    full_name: 'Полное название компании'
                    phone: '8 (800) 123 45-67'
                    email: site@yandex.ru
                    site: 'https://site'
                    owner: Владелец
                    responsible: Ответственный
                    responsible_phone: '8 (800) 123 45-67'
                    organization_type_id: 1
                    district_id: 1
                    education_license: null
                    medical_license: null
                    is_has_innovative_platform: false
                    status: pending
                    rejected_status_description: null
                properties:
                  error:
                    type: string
                    example: null
                  data:
                    type: object
                    example:
                      id: 1
                      name: 'Компания 1'
                      full_name: 'Полное название компании'
                      phone: '8 (800) 123 45-67'
                      email: site@yandex.ru
                      site: 'https://site'
                      owner: Владелец
                      responsible: Ответственный
                      responsible_phone: '8 (800) 123 45-67'
                      organization_type_id: 1
                      district_id: 1
                      education_license: null
                      medical_license: null
                      is_has_innovative_platform: false
                      status: pending
                      rejected_status_description: null
      tags:
        - Компании
    put:
      summary: 'Обновить компанию авторизованного юзера'
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Компании
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Краткое наименование организации'
                  example: 'Компания 1'
                full_name:
                  type: string
                  description: 'Полное наименование организации'
                  example: 'Полное название компании'
                phone:
                  type: string
                  description: 'Номер телефона организации'
                  example: '8 (800) 123 45-67'
                email:
                  type: string
                  description: 'Электронная почта организации'
                  example: site@yandex.ru
                site:
                  type: string
                  description: 'Ссылка на официальный сайт организации'
                  example: 'https://site'
                owner:
                  type: string
                  description: 'Руководитель организации'
                  example: Владелец
                responsible:
                  type: string
                  description: 'Ответственный за предоставление информации'
                  example: Ответственный
                responsible_phone:
                  type: string
                  description: 'Телефон ответственного за предоставление информации'
                  example: '8 (800) 123 45-67'
                organization_type_id:
                  type: integer
                  description: 'Тип организации'
                  example: 1
                district_id:
                  type: integer
                  description: Район
                  example: 1
                education_license:
                  type: object
                  description: 'optional Лицензия на осуществление образовательной деятельности'
                  example: []
                  properties:
                    number:
                      type: integer
                      description: 'Номер лицензии'
                      example: 1234
                    date:
                      type: string
                      description: 'Дата выдачи лицензии'
                      example: 22.05.2022
                    type:
                      type: string
                      description: 'Вид деятельности'
                      example: 'Дошкольное образование'
                medical_license:
                  type: object
                  description: 'optional Лицензия на осуществление медицинской деятельности'
                  example: []
                  properties:
                    number:
                      type: integer
                      description: 'Номер лицензии'
                      example: 1234
                    date:
                      type: string
                      description: 'Дата выдачи лицензии'
                      example: 22.05.2022
                is_has_innovative_platform:
                  type: boolean
                  description: 'Наличие инновационной площадки в организации'
                  example: false
              required:
                - name
                - full_name
                - phone
                - email
                - site
                - owner
                - responsible
                - responsible_phone
                - organization_type_id
                - district_id
                - is_has_innovative_platform
  /api/client/v1/users/login:
    post:
      summary: 'Войти в аккаунт'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Юзеры
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                login:
                  type: string
                  description: Логин
                  example: user1
                password:
                  type: string
                  description: Пароль
                  example: '1234'
              required:
                - login
                - password
      security: []
  /api/client/v1/users/check:
    post:
      summary: 'Проверить токен'
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Юзеры
tags:
  -
    name: 'Категории словарей'
    description: ''
  -
    name: Компании
    description: ''
  -
    name: Юзеры
    description: ''
components:
  securitySchemes:
    default:
      type: http
      scheme: bearer
      description: ''
security:
  -
    default: []
